my_string=input("Введите произвольную строку: ")
print ("длина строки:", len(my_string), "символов")
# print(type(my_string))
print (my_string.upper())
print (my_string.lower())
print (my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])